; Assetto Corsa Competizione
; In-Game Settings
;   Gain: 70
;   Minimum Force: 0
;   Damper: 10
;   Dynamic Damping: 100
;   Road Effects: 0
SEN = 1080
FF = 100
NDP = 20
NFR = 0
NIN = 3
INT = 4
FEI = 100
FOR = 100
SPR = 100
DPR = 50
BLI = 101
SHO = 100