; Assetto Corsa Evo
; In-Game Settings
;   Steering Lock: 1080
;   FFB Gain: 80
;   Dynamic Damping: 40
;   Road Effects: 0
;   Minimum Damper: 0
;   Damper Gain: 20
SEN = 1080
FF = 80
NDP = 15
NFR = 5
NIN = 0
INT = 2
FEI = 100
FOR = 100
SPR = 100
DPR = 100
BLI = 101
SHO = 100