; Assetto Corsa Rally
; In-Game Settings
;   Gain: 100
;   Minimum Force: 0
;   Damper: 30
;   Steering Lock: 900
SEN = 900
FF = 80
NDP = 4
NFR = 0
NIN = 0
INT = 4
FEI = 100
FOR = 100
SPR = 0
DPR = 100
BLI = 101
SHO = 100