; Automobilista 2
; In-Game Settings
;   Type: Default
;   Gain: 60
;   Low Force Boost: 0
;   FX: 20
;   Dampening: 18
;   Menu Spring Strength: 0
SEN = 1080
FF = 70
NDP = 25
NFR = 0
NIN = 0
INT = 4
FEI = 100
FOR = 100
SPR = 100
DPR = 100
BLI = 101
SHO = 100