; Automobilista 2
; In-Game Settings
;   Type: Default+
;   Gain: 60
;   Low Force Boost: 7
;   FX: 50
;   Dampening: 50
;   Menu Spring Strength: 10
SEN = 2530
FF = 100
FFS = 0
NDP = 22
NFR = 14
NIN = 10
INT = 4
FEI = 80
FOR = 100
SPR = 100
DPR = 100
BLI = 101
SHO = 100