; Le Mans Ultimate
; In-Game Settings
;   Force Feedback Effects: On
;   Invert Force Feedback: On
;   Force Feedback Strength: 70
;   Force Feedback Smoothing: 5
;   Minimum Steering Torque: 0
;   Colllision Strength: 40
;   Steering Torque Sensitivity: 100
;   Constant Steergin Force Effect: Off
SEN = 900
FF = 100
NDP = 15
NFR = 0
NIN = 0
INT = 3
FEI = 100
FOR = 100
SPR = 100
DPR = 100
BLI = 101
SHO = 100