; Poject Motor Racing
; In-Game Settings
;   Global Force Feedback Gain: 100
;   Low Force Boost: 0
;   Force Feedback Detail: 50
;   Force Feedback Smoothing: 10
;   Force Feedback Headroom: 100
;   Haptic Strength: 50
SEN = 900
FF = 100
FUL = 0
NDP = 5
NFR = 0
NIN = 1
INT = 1
FEI = 70
FOR = 100
SPR = 60
DPR = 100
BLI = 101
SHO = 100