; RaceRoom Racing Experience
; In-Game Settings
; Advanced Settings
;   Speed Sensitive Steering: 0
;   Steering Sensitivity: 50
; Force Feedback
;   Force Feedback: checked
;   Inverted Force Feedback: unchecked
;   FFB Strength: 80
;   FFB Minimum Force: 0
;   FFB Maximum Force: 80
;   Engine Vibrations: 4
;   Bump Amplification: 6
;   Gearshift Effects: 2
SEN = 2530
FF = 100
NDP = 20
NFR = 0
NIN = 0
INT = 2
FEI = 100
FOR = 100
SPR = 100
DPR = 100
BLI = 101
SHO = 100